### ISSUE TITLE
GoogleTagManager not found in allure-report script for Playwright (ts/js)

### ISSUE THREAD

**Issue by arundevtm** [aruiz-caritsqa/allure-single-html-file-js#3]
@aruiz-caritsqa 
Getting below error while running in Playwright

"... <script async="async" src="https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS"></script> ./allure-report/https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open './allure-report/https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS'"

I have used these version of the other relevant packages (for your reference):

  "devDependencies": {
    "@playwright/test": "1.36",
    "allure-playwright": "^2.4.0",
    "allure-single-html-file-js": "^0.0.4",
    "rimraf": "^5.0.1"
  },
  "dependencies": {
    "allure": "^0.0.0",
    "allure-combined": "^0.0.1",
    "allure-commandline": "^2.17.2"
  }

  "scripts": {
    "clean": "rimraf allure-report/ rimraf allure-results/",
    "test": "npm run clean && npx playwright test --config=playwright.config.ts",
    "allureCombine": "allure generate allure-results -o allure-report --clean && node ./node_modules/allure-single-html-file-js/combine.js allure-report"
  },

**Comment by aruiz-caritsqa** [comment]
Hi @arundevtm 

Can you attach a zipped copy of the `allure-report` directory with a subset of the files so that I can reproduce this issue. Can you also ensure you remove any proprietary and sensitive information from the reports.

Thanks
